[package]
name = "DesktopFile-Creator"
version = "0.1.0"
edition = "2021"
include = [
	"/src/help/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.6"

[profile.release]
overflow-checks = true
opt-level = 3
lto = true